---
# TODO optimize configure step (fftw, netcdf, hdf5, ...), see
# http://www.yambo-code.org/download/compiling.php
- name: Install required packages
  become: true
  become_user: "{{ root_user }}"
  apt:
      name: "{{ item }}"
      state: latest
  with_items:
    - build-essential
    - gfortran
    - openmpi-common
    - openmpi-bin
    - libopenmpi-dev
    - libfftw3-dev
    - libfftw3-bin
    - libfftw3-mpi-dev
    - liblapack-dev
    - libblas-dev
    - m4
    - wget

# Will only download once
- name: Get Yambo
  get_url: 
    url: "{{ yambo_url }}"
    dest: "{{ yambo_code_folder }}/{{ yambo_src_archive }}"
  register: yambo_download

- name: Extract yambo source
  unarchive:
    src: "{{ yambo_download.dest }}"
    dest: "{{ yambo_code_folder }}"
    remote_src: True
  when: yambo_download.changed

# Note: use ./configure --with-p2y-version=qexsd for QE 6.2 or higher with new xml schema
# See https://github.com/marvel-nccr/marvel-virtualmachine/issues/34
- name: Configure Yambo
  shell: ./configure 
  args:
    chdir: "{{ yambo_topdir }}"
    creates: "{{ yambo_topdir }}/Makefile"

- name: Make Yambo executables
  shell: "make {{ item.name }}"
  args:
    chdir: "{{ yambo_topdir }}"
    creates: "{{ yambo_topdir }}/bin/{{ item }}"
  with_items: "{{ yambo_executables }}"

- name: "Put a line in ~/.profile to add Yambo to the path"
  lineinfile:
    path: "${HOME}/.profile"
    line: "export PATH=${PATH}:{{ yambo_topdir }}/bin"

- include_role:
    name: release_notes
  vars:
    section: "Yambo"
    option: "version"
    value: "{{ yambo_version }}"
  when: release_notes is defined and release_notes

- include_role:
    name: release_notes
  vars:
    section: "Yambo"
    option: "usage"
    value: >-
       Yambo is compiled and installed in {{ yambo_topdir }}.
       Simply run 'yambo'.
  when: release_notes is defined and release_notes
